[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
swap = "FqzkXZdwYjurnUKetJCAvaUw5WAqbwzU6gZEwydeEfqS"

[programs.devnet]
swap="GSYCrqvf4xw2mP4DdYbPwKsNiKfnhhTSyv8p7h1SX28R"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "~/.config/solana/id.json"

[scripts]
test = "../node_modules/.bin/jest --preset ts-jest"
